"""Academic-workflow exporters: BibTeX, RIS, LaTeX, CSV."""
import csv
import io
import re
from typing import List
from app.schemas.research_state import ResearchState, Paper


def _bib_key(p: Paper) -> str:
    """Build a citation key like 'smith2024transformer'."""
    last = ""
    if p.authors:
        first_author = p.authors[0].split()[-1] if p.authors[0] else ""
        last = re.sub(r"[^a-zA-Z]", "", first_author).lower()
    year = str(p.year) if p.year else "nd"
    word = ""
    if p.title:
        for w in p.title.split():
            w = re.sub(r"[^a-zA-Z]", "", w).lower()
            if w and len(w) > 3:
                word = w
                break
    return f"{last or 'paper'}{year}{word or p.paper_id[:6]}"


def to_bibtex(papers: List[Paper]) -> str:
    lines = []
    for p in papers:
        key = _bib_key(p)
        authors = " and ".join(p.authors) if p.authors else ""
        entry = [
            f"@article{{{key},",
            f"  title = {{{p.title}}},",
        ]
        if authors:
            entry.append(f"  author = {{{authors}}},")
        if p.year:
            entry.append(f"  year = {{{p.year}}},")
        if p.source == "arxiv":
            entry.append(f"  archivePrefix = {{arXiv}},")
            entry.append(f"  eprint = {{{p.paper_id}}},")
        if p.pdf_url:
            entry.append(f"  url = {{{p.pdf_url}}},")
        entry.append("}")
        lines.append("\n".join(entry))
    return "\n\n".join(lines) + "\n"


def to_ris(papers: List[Paper]) -> str:
    """Standard RIS format for Zotero/Mendeley/EndNote."""
    out = []
    for p in papers:
        lines = ["TY  - JOUR"]
        if p.title:
            lines.append(f"TI  - {p.title}")
        for a in p.authors:
            lines.append(f"AU  - {a}")
        if p.year:
            lines.append(f"PY  - {p.year}")
        if p.abstract:
            lines.append(f"AB  - {p.abstract}")
        if p.pdf_url:
            lines.append(f"UR  - {p.pdf_url}")
        if p.source == "arxiv":
            lines.append(f"AN  - arXiv:{p.paper_id}")
        lines.append("ER  - ")
        out.append("\n".join(lines))
    return "\n\n".join(out) + "\n"


def to_latex(state: ResearchState) -> str:
    """Full LaTeX article with \\cite{} tags and bibliography."""
    bib_keys = [_bib_key(p) for p in state.papers]
    paper_id_to_key = {p.paper_id: bib_keys[i] for i, p in enumerate(state.papers)}
    paper_index_to_key = {i + 1: bib_keys[i] for i in range(len(state.papers))}

    essay = state.final_synthesis or ""

    # Replace [n] markers with \cite{key}
    def replace_marker(match):
        n = int(match.group(1))
        key = paper_index_to_key.get(n)
        if key:
            return f"\\cite{{{key}}}"
        return match.group(0)

    essay_with_cites = re.sub(r"\[(\d+)\]", replace_marker, essay)
    # Escape minimal LaTeX special chars in the essay (basic; assumes Markdown text)
    essay_with_cites = essay_with_cites.replace("&", "\\&").replace("%", "\\%").replace("#", "\\#")

    parts = [
        "\\documentclass{article}",
        "\\usepackage[utf8]{inputenc}",
        "\\usepackage{amsmath}",
        "\\usepackage{cite}",
        "\\usepackage{hyperref}",
        f"\\title{{Literature Synthesis: {_latex_escape(state.query)}}}",
        "\\author{Generated by STEM Synthesis}",
        "\\begin{document}",
        "\\maketitle",
        "",
        "\\section*{Synthesis}",
        essay_with_cites,
        "",
        "\\section*{Equations Extracted}",
    ]
    for a in state.analyses:
        for eq in a.equations:
            parts.append(f"\\paragraph{{{a.paper_id}}}")
            parts.append(f"\\begin{{equation*}} {eq.latex} \\end{{equation*}}")
            if eq.plain_english:
                parts.append(_latex_escape(eq.plain_english))
            parts.append("")
    parts += [
        "",
        "\\begin{thebibliography}{99}",
    ]
    for i, p in enumerate(state.papers):
        key = bib_keys[i]
        authors = ", ".join(p.authors) if p.authors else ""
        year = str(p.year) if p.year else "n.d."
        parts.append(f"\\bibitem{{{key}}} {_latex_escape(authors)}. \\textit{{{_latex_escape(p.title)}}}. {year}." +
                     (f" arXiv:{p.paper_id}." if p.source == 'arxiv' else ""))
    parts.append("\\end{thebibliography}")
    parts.append("\\end{document}")
    _ = paper_id_to_key  # reserved for future use
    return "\n".join(parts) + "\n"


def _latex_escape(s: str) -> str:
    if not s:
        return ""
    repls = {
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
        "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    out = s
    for k, v in repls.items():
        out = out.replace(k, v)
    return out


def to_csv(state: ResearchState) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["paper_id", "title", "authors", "year", "methodology", "limitations", "key_finding", "equations"])
    paper_meta = {p.paper_id: p for p in state.papers}
    for row in state.comparison_table:
        meta = paper_meta.get(row.paper_id)
        title = meta.title if meta else ""
        authors = "; ".join(meta.authors) if meta and meta.authors else ""
        year = str(meta.year) if meta and meta.year else ""
        writer.writerow([
            row.paper_id,
            title,
            authors,
            year,
            row.methodology,
            row.limitations,
            row.key_finding,
            row.equations,
        ])
    return buf.getvalue()
